# Generated by Django 4.1.3 on 2023-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerevalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountpass',
            name='beautyTitle',
            field=models.CharField(default='пер.', max_length=255, verbose_name='краткое название'),
        ),
        migrations.AlterField(
            model_name='mouser',
            name='email',
            field=models.CharField(max_length=100, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='mouser',
            name='phone',
            field=models.IntegerField(max_length=12, verbose_name='Телефон'),
        ),
    ]
